// Generated by scripts/build-data.mjs — do not edit by hand.
export const TOTAL_QUESTIONS = 7106
export const TOPIC_COUNTS: Record<number, number> = {"1":531,"2":662,"3":502,"4":426,"5":243,"6":259,"7":252,"8":603,"9":179,"10":260,"11":256,"12":134,"13":378,"14":414,"15":156,"16":190,"17":330,"18":176,"19":133,"20":222,"21":126,"22":141,"23":146,"24":103,"25":284}
