// Generated by scripts/build-data.mjs — do not edit by hand.
export const TOTAL_QUESTIONS = 7138
export const TOPIC_COUNTS: Record<number, number> = {"1":531,"2":662,"3":521,"4":433,"5":243,"6":260,"7":253,"8":603,"9":181,"10":263,"11":256,"12":135,"13":379,"14":415,"15":156,"16":191,"17":331,"18":176,"19":135,"20":234,"21":102,"22":141,"23":149,"24":103,"25":285}
