// Generated by scripts/build-splash.mjs
export const SPLASH_DEVICES: [number, number, number][] = [[440,956,3],[402,874,3],[430,932,3],[393,852,3],[428,926,3],[390,844,3],[375,812,3],[414,896,3],[414,896,2],[375,667,2]]
