// Regenerates derived data from public/data/questions.json:
//   public/data/topics/<id>.json  — one file per topic (smaller downloads for topic quizzes)
//   src/lib/questionCounts.ts     — counts used by Home/Topic without downloading anything
// Run after changing questions.json:  npm run data
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const all = JSON.parse(readFileSync('public/data/questions.json', 'utf8'))
const byTopic = {}
for (const q of all) (byTopic[q.t] ||= []).push(q)

mkdirSync('public/data/topics', { recursive: true })
for (const [t, qs] of Object.entries(byTopic)) writeFileSync(`public/data/topics/${t}.json`, JSON.stringify(qs))

const counts = Object.fromEntries(Object.entries(byTopic).map(([t, qs]) => [t, qs.length]))
writeFileSync('src/lib/questionCounts.ts',
`// Generated by scripts/build-data.mjs — do not edit by hand.
export const TOTAL_QUESTIONS = ${all.length}
export const TOPIC_COUNTS: Record<number, number> = ${JSON.stringify(counts)}
`)
console.log(`${all.length} questions, ${Object.keys(byTopic).length} topics`)

// Every road sign image, so the service worker can download them all for offline use.
import { readdirSync } from 'node:fs'
const signs = readdirSync('public/images/signs').filter(f => /\.(png|jpe?g|webp|gif|svg)$/i.test(f)).sort()
writeFileSync('public/data/signs.json', JSON.stringify(signs))
console.log(`${signs.length} sign images listed`)
