// Generates iOS launch images (light + dark) for "Add to Home Screen".
// iOS shows these while the web app starts; without them it shows plain white.
import { createRequire } from 'node:module'
const sharp = createRequire(import.meta.url)('sharp') // dev-only tool (installed globally or as a Next dependency)
import { writeFileSync } from 'node:fs'

export const DEVICES = [
  [440, 956, 3], [402, 874, 3], [430, 932, 3], [393, 852, 3], [428, 926, 3],
  [390, 844, 3], [375, 812, 3], [414, 896, 3], [414, 896, 2], [375, 667, 2],
]
const THEMES = { light: '#FAFAF8', dark: '#0B0B0A' }
const mark = (s) => `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 64 64">
<rect width="64" height="64" rx="14" fill="#FF7A00"/><g fill="#0B0B0A">
<polygon points="21.2,8.9 27.8,8.9 19.4,55.1 10.6,55.1"/><polygon points="36.2,8.9 42.8,8.9 53.4,55.1 44.6,55.1"/>
<rect x="29.4" y="10.5" width="5.2" height="9"/><rect x="29.0" y="25.5" width="6.0" height="11"/><rect x="28.6" y="42.5" width="6.8" height="12.6"/></g></svg>`

for (const [w, h, r] of DEVICES) {
  const W = w * r, H = h * r, m = 96 * r
  for (const [name, bg] of Object.entries(THEMES)) {
    await sharp({ create: { width: W, height: H, channels: 3, background: bg } })
      .composite([{ input: Buffer.from(mark(m)), left: Math.round((W - m) / 2), top: Math.round((H - m) / 2) }])
      .png({ compressionLevel: 9, palette: true })
      .toFile(`public/splash/${name}-${W}x${H}.png`)
  }
}
writeFileSync('src/lib/splashDevices.ts',
  `// Generated by scripts/build-splash.mjs\nexport const SPLASH_DEVICES: [number, number, number][] = ${JSON.stringify(DEVICES)}\n`)
console.log('done')
